@startuml
left to right direction
actor "User" as User

package "Image Editing" {

  usecase "Open Image\nfrom Gallery" as UC_Open
  usecase "Crop Image" as UC_Crop
  usecase "Rotate / Flip Image" as UC_Rotate
  usecase "Apply Filters" as UC_Filter
  usecase "Adjust Filter Parameters\n(Brightness, Contrast,\nSaturation)" as UC_Adjust
  usecase "Enhance Image" as UC_Enhance
  usecase "Save Edited Image" as UC_Save

}

User --> UC_Crop
User --> UC_Rotate
User --> UC_Filter
User --> UC_Enhance

UC_Crop ..> UC_Open : <<include>>
UC_Rotate ..> UC_Open : <<include>>
UC_Filter ..> UC_Open : <<include>>
UC_Enhance ..> UC_Open : <<include>>

UC_Filter ..> UC_Adjust : <<include>>

UC_Crop ..> UC_Save : <<include>>
UC_Rotate ..> UC_Save : <<include>>
UC_Filter ..> UC_Save : <<include>>
UC_Enhance ..> UC_Save : <<include>>

@enduml