import { useState } from "react";
import { useNavigate } from "react-router";
import {
  Languages,
  ArrowLeft,
  ArrowLeftRight,
  Volume2,
  Copy,
  Download,
  Sparkles,
  FileText,
  Loader2,
} from "lucide-react";
import { Button } from "../components/ui/button";
import { Textarea } from "../components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";
import { toast } from "sonner";

type Language = {
  code: string;
  name: string;
  flag: string;
};

export function Translate() {
  const navigate = useNavigate();
  const [sourceText, setSourceText] = useState("");
  const [translatedText, setTranslatedText] = useState("");
  const [sourceLang, setSourceLang] = useState("en");
  const [targetLang, setTargetLang] = useState("vi");
  const [isTranslating, setIsTranslating] = useState(false);

  const languages: Language[] = [
    { code: "en", name: "English", flag: "🇬🇧" },
    { code: "vi", name: "Vietnamese", flag: "🇻🇳" },
    { code: "zh", name: "Chinese", flag: "🇨🇳" },
    { code: "ja", name: "Japanese", flag: "🇯🇵" },
    { code: "ko", name: "Korean", flag: "🇰🇷" },
    { code: "es", name: "Spanish", flag: "🇪🇸" },
    { code: "fr", name: "French", flag: "🇫🇷" },
    { code: "de", name: "German", flag: "🇩🇪" },
    { code: "it", name: "Italian", flag: "🇮🇹" },
    { code: "pt", name: "Portuguese", flag: "🇵🇹" },
  ];

  const handleTranslate = () => {
    if (!sourceText.trim()) {
      toast.error("Please enter text to translate");
      return;
    }

    setIsTranslating(true);

    // Simulate Gemini API translation
    setTimeout(() => {
      const translations: Record<string, string> = {
        vi: "Đây là bản dịch mẫu được tạo bởi Google Gemini AI. Trong môi trường thực tế, văn bản của bạn sẽ được dịch chính xác sang ngôn ngữ mục tiêu với ngữ cảnh và sắc thái phù hợp.",
        zh: "这是由 Google Gemini AI 生成的示例翻译。在实际环境中，您的文本将被准确翻译成具有适当上下文和细微差别的目标语言。",
        ja: "これは Google Gemini AI によって生成されたサンプル翻訳です。実際の環境では、テキストは適切なコンテキストとニュアンスでターゲット言語に正確に翻訳されます。",
        es: "Esta es una traducción de muestra generada por Google Gemini AI. En un entorno real, su texto se traducirá con precisión al idioma de destino con el contexto y los matices adecuados.",
        en: "This is a sample translation generated by Google Gemini AI. In a real environment, your text will be accurately translated to the target language with proper context and nuances.",
      };

      setTranslatedText(
        translations[targetLang] ||
          "Translation generated by Gemini AI. Your text will be accurately translated with proper context."
      );
      setIsTranslating(false);
      toast.success("Translation completed!");
    }, 1500);
  };

  const handleSwapLanguages = () => {
    const tempLang = sourceLang;
    setSourceLang(targetLang);
    setTargetLang(tempLang);
    const tempText = sourceText;
    setSourceText(translatedText);
    setTranslatedText(tempText);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(translatedText);
    toast.success("Copied to clipboard!");
  };

  const handleDownload = () => {
    const blob = new Blob([translatedText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "translation.txt";
    a.click();
    toast.success("Translation downloaded!");
  };

  return (
    <div className="h-full flex flex-col bg-neutral-50">
      {/* Header */}
      <div className="bg-white border-b border-neutral-200 px-4 py-3">
        <div className="flex items-center gap-3 mb-2">
          <button
            onClick={() => navigate("/")}
            className="p-2 hover:bg-neutral-100 rounded-lg"
          >
            <ArrowLeft className="size-5" />
          </button>
          <h1 className="text-xl">Translate</h1>
        </div>
        <div className="flex items-center gap-2 text-sm text-neutral-600">
          <Sparkles className="size-4" />
          <p>Powered by Google Gemini AI</p>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-4 space-y-4">
        {/* Language Selection */}
        <div className="bg-white border border-neutral-200 rounded-2xl p-4">
          <div className="flex items-center gap-3">
            <div className="flex-1">
              <label className="text-xs text-neutral-600 mb-2 block">From</label>
              <Select value={sourceLang} onValueChange={setSourceLang}>
                <SelectTrigger className="h-11">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {languages.map((lang) => (
                    <SelectItem key={lang.code} value={lang.code}>
                      <span className="flex items-center gap-2">
                        <span>{lang.flag}</span>
                        <span>{lang.name}</span>
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <button
              onClick={handleSwapLanguages}
              className="p-3 bg-blue-100 rounded-full hover:bg-blue-200 transition-colors mt-6"
            >
              <ArrowLeftRight className="size-5 text-blue-600" />
            </button>

            <div className="flex-1">
              <label className="text-xs text-neutral-600 mb-2 block">To</label>
              <Select value={targetLang} onValueChange={setTargetLang}>
                <SelectTrigger className="h-11">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {languages.map((lang) => (
                    <SelectItem key={lang.code} value={lang.code}>
                      <span className="flex items-center gap-2">
                        <span>{lang.flag}</span>
                        <span>{lang.name}</span>
                      </span>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>

        {/* Source Text */}
        <div className="bg-white border border-neutral-200 rounded-2xl overflow-hidden">
          <div className="border-b border-neutral-200 px-4 py-2 flex items-center justify-between">
            <span className="text-sm font-medium">Enter Text</span>
            <button className="p-1.5 hover:bg-neutral-100 rounded-lg">
              <Volume2 className="size-4 text-neutral-600" />
            </button>
          </div>
          <Textarea
            value={sourceText}
            onChange={(e) => setSourceText(e.target.value)}
            placeholder="Type or paste text to translate..."
            className="min-h-[150px] border-0 focus-visible:ring-0 resize-none"
          />
          <div className="border-t border-neutral-200 px-4 py-2 flex items-center justify-between">
            <span className="text-xs text-neutral-500">
              {sourceText.length} characters
            </span>
            <Button
              onClick={handleTranslate}
              disabled={isTranslating || !sourceText.trim()}
              size="sm"
              className="gap-2"
            >
              {isTranslating ? (
                <>
                  <Loader2 className="size-4 animate-spin" />
                  Translating...
                </>
              ) : (
                <>
                  <Languages className="size-4" />
                  Translate
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Translated Text */}
        {translatedText && (
          <div className="bg-white border border-neutral-200 rounded-2xl overflow-hidden">
            <div className="border-b border-neutral-200 px-4 py-2 flex items-center justify-between">
              <span className="text-sm font-medium">Translation</span>
              <div className="flex gap-1">
                <button
                  onClick={handleCopy}
                  className="p-1.5 hover:bg-neutral-100 rounded-lg"
                >
                  <Copy className="size-4 text-neutral-600" />
                </button>
                <button className="p-1.5 hover:bg-neutral-100 rounded-lg">
                  <Volume2 className="size-4 text-neutral-600" />
                </button>
              </div>
            </div>
            <div className="p-4 min-h-[150px]">
              <p className="text-base leading-relaxed">{translatedText}</p>
            </div>
            <div className="border-t border-neutral-200 px-4 py-2 flex justify-end">
              <Button
                onClick={handleDownload}
                variant="outline"
                size="sm"
                className="gap-2"
              >
                <Download className="size-4" />
                Download
              </Button>
            </div>
          </div>
        )}

        {/* Features */}
        <div className="bg-gradient-to-br from-blue-50 to-purple-50 border border-blue-200 rounded-2xl p-4">
          <h3 className="font-semibold mb-3 flex items-center gap-2">
            <Sparkles className="size-4 text-purple-600" />
            Features
          </h3>
          <div className="space-y-2 text-sm text-neutral-700">
            <div className="flex items-start gap-2">
              <span className="text-blue-600">•</span>
              <span>Supports 100+ languages</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-blue-600">•</span>
              <span>Context-aware translations</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-blue-600">•</span>
              <span>Powered by Google Gemini AI</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="text-blue-600">•</span>
              <span>Instant translation results</span>
            </div>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="space-y-2">
          <p className="text-sm font-medium text-neutral-600">Quick Actions</p>
          <div className="grid grid-cols-2 gap-2">
            <button
              onClick={() => navigate("/ocr")}
              className="bg-white border border-neutral-200 rounded-xl p-3 hover:border-blue-300 hover:shadow-sm transition-all text-left"
            >
              <FileText className="size-5 text-blue-600 mb-2" />
              <p className="text-sm font-medium">Extract & Translate</p>
              <p className="text-xs text-neutral-500">OCR + Translation</p>
            </button>
            <button
              onClick={() => navigate("/scan")}
              className="bg-white border border-neutral-200 rounded-xl p-3 hover:border-blue-300 hover:shadow-sm transition-all text-left"
            >
              <Sparkles className="size-5 text-purple-600 mb-2" />
              <p className="text-sm font-medium">Scan & Translate</p>
              <p className="text-xs text-neutral-500">Camera + Translation</p>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
